---
name: ExtUtils-H2PM
version: 0.02
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: automatically generate perl modules to wrap C header files
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  Test::Output: 0
requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Module::Build: 0.35
provides:
  ExtUtils::H2PM:
    file: lib/ExtUtils/H2PM.pm
    version: 0.02
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
